### PR TITLE
Omnipay 2.0

### PR DESCRIPTION
**Pull request by bummzack**
Implemented all supported Omnipay 2.x gateway services: Purchase, Authorize, Capture, Void, Refund.

Implemented support for gateways that confirm success via asynchronous notifications.
Introduced namespaces for all classes that aren't DataObjects.
Introduced a factory to create payment services.
Added gridfield actions to enable capture, refund and void of payments via CMS.

Updated/added a lot of unit-tests (services are covered 100%).
Updated readme files.

Config is backwards compatible with 1.x.
The API is in large parts backwards compatible with 1.x but now uses namespaces.

### CODE REVIEW

**Comment by bummzack** [comment]
I know, this is a big one and it might break setups that already run on the `2.0.x-dev` branch, because they needed Omnipay 2.x compatibility.

My suggestion is to create some beta tags that will give these people a stable point to fall back to.

Suggestions:
- `2.0-beta-1`: Basically the latest commit that is omnipay 2.x compatible but doesn't introduce new API [Link](https://github.com/silverstripe/silverstripe-omnipay/commit/95bb32ce22492b270cd03dec5756521838edfc24)
- `2.0-beta-2`: Module with the new config-API [Link](https://github.com/silverstripe/silverstripe-omnipay/commit/1bc7b4844e598f948bd924af51cc4dc3ce04c648)
- `2.0-rc1`: I suggest this tag once this PR is merged.

Thoughts? @markguinn, @wilr, @anselmdk

**Comment by anselmdk** [comment]
@bummzack do I understand correctly that you suggest to tag the current `2.0` branch with `2.0-beta-1`?
I'm not sure what `2.0-beta-2` would be for then, but maybe it's because I'm just not too much into what's been happening here, but overall I think this sounds reasonable.

**Comment by bummzack** [comment]
I'd create two different beta tags, one for the omnipay 2 compatible module and one where the new config-api was introduced (as this will generate deprecation warnings in shop). Then another tag "release-candidate" for the changes introduced with this PR.

If you look closely, you can see that I referenced two different commits for the different tags above.

**Comment by anselmdk** [comment]
THAT makes sense, thanks for explaining, and sorry for the confusion.

**Comment by markguinn** [comment]
I think I'd be more comfortable using alpha for the first tags and beta for the second. But I don't feel strongly about it.

**Comment by bummzack** [comment]
I'm not fixated on the tag names… just something we can tell to developers who need one of these versions.

@markguinn What permissions do you have on this repo? Can you still create tags, merge PRs etc?

**Comment by markguinn** [comment]
I don't have any more than you I think. @wilr does though.

**Comment by wilr** [comment]
:) all the power. I'll setup a managing group

**Comment by bummzack** [comment]
@wilr Awesome, thanks!

**Comment by bummzack** [comment]
Unless there are objections, I'm going through with the tagging and merging?
Tags will be: `2.0-alpha`, `2.0-beta` and `2.0-rc-1`. I'll also create a changelog to provide some description.

**Pull request merged**
