### PR TITLE
UNFINISHED: saved cards

### PR DESCRIPTION
**Pull request by markguinn**
I’m working on an addition to the silverstripe-omnipay (and eventually shop) module that allows one to utilise omnipay’s credit card tokenising features if present (https://github.com/omnipay/omnipay#token-billing). This is just a temporary PR to discuss. There will be a corresponding PR to ss-shop to utilize this functionality. I'm currently using this on a beta site and it's working well using PayPal's vault API (https://github.com/omnipay/paypal/pull/21).

Jeremy mentioned that @halkyon and @chillu might have some thoughts or input on the architecture.

### CODE REVIEW

**Comment by jedateach** [comment]
@markguinn what are your thoughts on the status of this? Did you ever get it to production?

**Comment by markguinn** [comment]
Yes, we're launching a site that uses this code next month. I hadn't pushed it any further because I realized I was using omnipay 2.0 and haven't had time to test further. The code is working though. Ideally it would need tests and it would probably need to be tested against Stripe instead of Paypal REST which is what we're using.

**Comment by jedateach** [comment]
I would ultimately like to have all gateways mock tested through the silverstripe-omnipay module.

**Comment by wilr** [comment]
@bummzack Do we want to pull this into 2.0 branch and review the tests again?

**Comment by bummzack** [comment]
This looks like a really useful addition to the module, although it would require some refactoring and should go into the 2.x branch instead.
@markguinn Is this PR the most updated version of what you did? Is the functionality complete?

**Pull request closed without merging**
